---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: house-price-app
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: house-price-predictor
  source:
    repoURL: https://github.com/pushpendras21/house-price-predictor.git
    targetRevision: HEAD
    path: deployment/kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
      
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
