apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: house-price-predictor
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Working with CI workflow-action and CD Project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the argocd namespace in the same cluster
  # Destination clusters can be identified by 'server', 'name', or both.
  destinations:
  - namespace: default
    server: https://kubernetes.default.svc
 
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

